add amended user-agent and/or x-goog-api-client header for audit logs and partner attribution (#238)
* prefer tls-roots if both tls-webpki-roots and tls-roots features are set

I was getting:

```
error[E0592]: duplicate definitions with name `init_tls_config`
   --> gcloud-sdk/src/api_client.rs:261:5
    |
254 |     fn init_tls_config(domain_name: String) -> tonic::transport::ClientTlsConfig {
    |     ---------------------------------------------------------------------------- other definition for `init_tls_config`
...
261 |     fn init_tls_config(domain_name: String) -> tonic::transport::ClientTlsConfig {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definitions for `init_tls_config`
```

on `cargo test` from a clean checkout of `upstream/master`. Not 100%
sure how I am getting tls-webpki-roots set, as the default is set to
tsl-roots, though.

* add amended user-agent and/or x-goog-api-client header for audit logs and partner attribution

* remove unused methods

---------

Co-authored-by: Abdulla Abdurakhmanov <me@abdolence.dev>